### ISSUE TITLE
can you give a docker image address? 

### ISSUE THREAD

**Issue by wangsheng1991** [zhangfuyang/Conv-MPN#1]
Can you give a docker image address? I found the corner detection need torch0.4, but Conv -MPN need 1.2

**Comment by zhangfuyang** [comment]
Sorry that we are not going to make a docker image for now. You can download corner detection results from [here](https://drive.google.com/open?id=1AikD1FlNfpFqJy3g-mx8V2KtpYKDzV0Q) if you don't want to train the detector.
